### ISSUE TITLE
카탈리나에서 프로그램 실행이 되지 않습니다.

### ISSUE THREAD

**Issue by slowkuma** [akirose/ds4free-release#2]
![System](https://user-images.githubusercontent.com/7185156/76402486-db2c2800-63c6-11ea-991f-86bacc626aaa.png)
![Report](https://user-images.githubusercontent.com/7185156/76402495-dd8e8200-63c6-11ea-9acf-1c08226859d9.png)
해당 메세지를 출력 하면서 종료 됩니다.

**Comment by akirose** [comment]
코드 서명 문제로 Mojave에서도 실행이 안되는 것을 확인하여 다시 업로드 하였습니다.
