### ISSUE TITLE
환경설정의 키맵에서 할당된 키 값이 표시 되었으면 합니다.

### ISSUE THREAD

**Issue by slowkuma** [akirose/ds4free-release#3]
![KayMap](https://user-images.githubusercontent.com/7185156/76481244-5851ae80-6454-11ea-85f9-b8c7a12b2bd0.png)

현재 할당된 키가 어떤 키가 할당 되어 있는지 숫자만 봐서는 알 수 없어 하나씩 눌러보면서 확인 해야 합니다.
할당된 키의 명칭이 표시 되면 좋겠습니다.

**Comment by akirose** [comment]
v1.0.2 에서 해당 기능 구현 되었습니다
