### ISSUE TITLE
환결설정 신규 키맵 설정때 기본 설정을 복사 해 오면 좋겠습니다.

### ISSUE THREAD

**Issue by slowkuma** [akirose/ds4free-release#4]
![KeyMapEmpty](https://user-images.githubusercontent.com/7185156/76481493-ffcee100-6454-11ea-9155-97ddf9332ae7.png)

환경설정에서 신규 설정값을 만들었을때 기본 설정값을 복사 해 오거나
또는 특정 하나에서 복사 해 올 수 있는 기능이 있었으면 합니다.

**Comment by akirose** [comment]
v1.0.2 에서 기능 구현 되었습니다.
