### ISSUE TITLE
4.0.0 대응 가능할까요

### ISSUE THREAD

**Issue by dhhomie** [akirose/ds4free-release#5]
@akirose 
최근 리모트 플레이 업데이트 이후로 작동하지않는것같아요.
죄송하지만 혹시 업데이트 예정이 있을까요?

**Comment by akirose** [comment]
이번에 업데이트가 크게 되서 다시 검토중입니다. :)

**Comment by dhhomie** [comment]
@akirose 
작동하지 않는건 어플의 업데이트가 아니라 맥OS의 업데이트 때문이었던듯합니다.
[csrutil을 비활성화](https://www.imore.com/how-turn-system-integrity-protection-macos)하면 작동하는듯합니다!
다만 이걸로 컴퓨터나 앞으로의 업데이트에 어떤 영향이 있을지는 모르겠지만^^;

**Comment by akirose** [comment]
@dhhomie 
SIP 비활성화 시 동작하다니 생각지도 못한 부분이네요. ^^;;
SIP를 비활성화하고 사용하시면 아무래도 OS 영역의 파일을 수정할 수 있게 되어서 보안에 취약해질 수는 있습니다.
현재는 리모트플레이 앱 내에 강제로 코드를 주입시켜 실행하는 형태라 아무래도 제약사항이 생길 수 있어서 다른 방식을 고려중인데 잘 되면 다른 방법으로 공유해보도록 하겠습니다. :)

**Comment by akirose** [comment]
@dhhomie 
readme에 해결방법 추가 하였습니다.
SIP 비활성화 하지 않고도 사용할 수 있는 방법이 있으니 참고하시기 바랍니다. ^^
