### ISSUE TITLE
맥북 M1에서 동작을 안하네여

### ISSUE THREAD

**Issue by oorururu** [akirose/ds4free-release#7]
readme에 있는 방법으로 터미널에 sudo ~~ 명령어를 적용했으나 no such라고 나옵니다. 

아직 대응 방법이 없는건가요?

**Comment by akirose** [comment]
codesign 명령어가 없으시면 앱 스토어에서 Xcode를 다운받은 후에 실행하셔서 Command Line Tools를 설치한 후에 다시 시도해보세요.

**Comment by oorururu** [comment]
메일 답장 감사합니다. 
 
답장에 나와있는것 처럼 해보았으나
 
sudo codesign -fs - /Application/RemotePlay.app 
/Application/RemotePlay.app: No such file or directory
 
라고 나오네요
 
M1 맥북이라서 그런건지.. 
참고로 당연히 정식 리모트 프로그램은 정상적으로 설치되어있어요
 
 
 
 
 
 
-----Original Message-----

**Comment by akirose** [comment]
리모트 플레이가 설치된 경로가 다른 모양입니다. 설치된 경로를 확인하신 후에 변경해보세요.

**Comment by oorururu** [comment]
감사합니다. 해결했네여
 
sudo codesign -fs - /Application/RemotePlay.app 경로중에 애플리케이션 뒤에 sudo codesign -fs - /Applications/RemotePlay.app 위에 처럼 s를 붙이니 정상 작동하네여
 
 
-----Original Message-----

**Comment by akirose** [comment]
아... 설명의 경로가 잘못 되었었군요.
정정하였습니다. 
감사합니다. :)
